name: Bleeding edge
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows/.github/workflows/github-composite-action-bleeding-edge.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      ref: ""${{ github.ref }}"
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"